import express, { Request, Response } from 'express';
import cors from 'cors';
import path from 'path';
import fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import dotenv from 'dotenv';
import { generateWidgetCode, testAIConnection } from './services/aiService';
import { scaffoldWidget } from './services/scaffoldWidget';

dotenv.config();

const execAsync = promisify(exec);
const app = express();
const PORT = process.env.PORT || 8000;

app.use(cors());
app.use(express.json());

// --- Basic Health Check ---
app.get('/', (req: Request, res: Response) => {
  res.send('<h1>🚀 WidgetForge API</h1><p>The backend is live and ready to bundle widgets.</p>');
});

// --- Routes ---
app.get('/api/health', (req: Request, res: Response) => {
  res.json({ status: 'ok', message: 'WidgetForge Generator Backend is running.' });
});

app.get('/api/ai/status', async (req: Request, res: Response) => {
  try {
    const result = await testAIConnection();
    res.json({ success: true, ...result });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// --- Shared Core Build Logic ---
async function buildWidgetPackage(
  widgetName: string,
  description: string,
  aiXml: string,
  aiJsx: string,
  res: Response,
  aiCss?: string,
  dependencies?: Record<string, string>
) {
  console.log(`Initiating build for ${widgetName}`);
  const tempDir = path.join(__dirname, '..', 'temp', `${Date.now()}-${widgetName}`);

  try {
    // Phase 1: Scaffold
    console.log(`[1/4] Scaffolding widget: ${widgetName}`);
    const genDir = path.join(tempDir, widgetName);
    await scaffoldWidget(genDir, { widgetName, description, dependencies });

    // Phase 2: Inject AI-generated code
    console.log(`[2/4] Injecting generated code...`);

    // --- XML Corrections ---
    const xmlFile = path.join(genDir, 'src', `${widgetName}.xml`);
    const expectedId = `com.widgetforge.${widgetName.toLowerCase()}.${widgetName}`;
    let finalXml = aiXml;

    // Fix widget ID in the root <widget> tag
    if (!finalXml.includes(`id="${expectedId}"`)) {
      finalXml = finalXml.replace(/(<widget\s+[^>]*?id=")[^"]*(")/i, `$1${expectedId}$2`);
    }

    // Fix missing/empty <propertyGroup caption>
    if (finalXml.includes('<propertyGroup>') || finalXml.includes('<propertyGroup caption="">')) {
      finalXml = finalXml.replace(/<propertyGroup\s*>/g, '<propertyGroup caption="General">');
      finalXml = finalXml.replace(/<propertyGroup\s+caption=["']['"]?\s*>/g, '<propertyGroup caption="General">');
    } else if (finalXml.includes('<property') && !finalXml.includes('<propertyGroup')) {
      finalXml = finalXml.replace(
        /(<properties>)([\s\S]*?)(<\/properties>)/i,
        (_, open, props, close) =>
          `${open}\n        <propertyGroup caption="General">${props}</propertyGroup>\n    ${close}`
      );
    }

    // Ensure <properties> element always exists — Mendix requires it even if empty.
    if (!finalXml.includes('<properties')) {
      finalXml = finalXml.replace(
        /(<\/widget>)/i,
        '    <properties>\n    </properties>\n$1'
      );
    }

    // Remove invalid XML child elements generated by AI
    const invalidTags = ['translatable', 'minimumValue', 'maximumValue', 'defaultValue', 'isList', 'required', 'isDefault', 'onChange'];
    invalidTags.forEach(tag => {
      finalXml = finalXml.replace(new RegExp(`\\s*<${tag}>[\\s\\S]*?<\\/${tag}>\\s*`, 'gi'), '');
      finalXml = finalXml.replace(new RegExp(`\\s*<${tag}\\s*\\/?>\\s*`, 'gi'), '');
    });

    // --- XML Finalization ---
    // 1. Remove any existing XML declarations (case-insensitive)
    finalXml = finalXml.replace(/<\?xml[\s\S]*?\?>/gi, '');
    
    // 2. Remove any comments that might be at the very top (before the root tag)
    finalXml = finalXml.replace(/^\s*<!--[\s\S]*?-->\s*/, '');

    // 3. Trim and prepend the required declaration
    finalXml = `<?xml version="1.0" encoding="utf-8"?>\n` + finalXml.trim();

    await fs.writeFile(xmlFile, finalXml);

    // --- JSX Corrections ---
    const entryFile = path.join(genDir, 'src', `${widgetName}.tsx`);
    let cleanedJsx = aiJsx.replace(
      /import\s+\{\s*([^}]*)\s*\}\s+from\s+['"]react['"];?/g,
      (match, p1) => {
        const imports = p1.split(',').map((s: string) => s.trim()).filter((s: string) => s !== 'createElement');
        return imports.length === 0 ? '' : `import { ${imports.join(', ')} } from "react";`;
      }
    );

    // Inject CSS import if provided
    if (aiCss && !cleanedJsx.includes(`./ui/${widgetName}.css`)) {
      cleanedJsx = `import "./ui/${widgetName}.css";\n` + cleanedJsx;
    }

    // Safety net: strip any mendix/* or @mendix/* imports the AI may have hallucinated.
    // These modules do not exist in the widget scaffold and will break the build.
    cleanedJsx = cleanedJsx.replace(/^import\s+.*from\s+['"]((?:@mendix|mendix)[^'"]*)['"];?\s*$/gm, '');

    // No watermark injection for TSX

    await fs.writeFile(entryFile, cleanedJsx);

    if (aiCss) {
      await fs.writeFile(path.join(genDir, 'src', 'ui', `${widgetName}.css`), aiCss);
    }

    // Phase 3: Install & Build
    try {
      await execAsync('npm install --legacy-peer-deps', {
        cwd: genDir,
        timeout: 600000,
        env: { ...process.env, CI: 'true' }
      });
    } catch (installErr: any) {
      const details = installErr.stderr || installErr.stdout || installErr.message;
      throw new Error(`npm install failed: ${details.slice(0, 1000)}`);
    }

    try {
      console.log(`[3/4] Building widget...`);
      await execAsync('echo y | npm run build', {
        cwd: genDir,
        timeout: 600000,
        env: { ...process.env, CI: 'true' }
      });
    } catch (buildErr: any) {
      // Return the raw stderr/stdout for better debugging in the UI
      const details = buildErr.stderr || buildErr.stdout || buildErr.message;
      throw new Error(details); 
    }

    // Inject CSS into the generated MPK (Mendix build tools omit it by default)
    if (aiCss) {
      try {
        const packagePathXml = 'com/widgetforge';
        const packageName = widgetName.toLowerCase();
        const sourceCssFile = path.join(genDir, 'src', 'ui', `${widgetName}.css`);

        // Locate the generated .mpk file dynamically
        const distDir = path.join(genDir, 'dist');
        const allDistFiles = await fs.readdir(distDir, { recursive: true });
        const mpkFilename = (allDistFiles as string[]).find(f => f.endsWith('.mpk'));
        if (!mpkFilename) throw new Error('Could not find generated .mpk in dist/');

        const finalMpkPath = path.resolve(distDir, mpkFilename);
        const cssBuffer = await fs.readFile(sourceCssFile);
        const zipCssPath = `${packagePathXml}/${packageName}/ui/${widgetName}.css`;

        const AdmZip = require('adm-zip');
        const zip = new AdmZip(finalMpkPath);

        // Add the CSS file to the archive
        zip.addFile(zipCssPath, cssBuffer, 'Injected by WidgetForge');

        // Update package.xml manifest to reference the CSS file
        let packageXmlContent = zip.readAsText('package.xml');
        if (packageXmlContent && !packageXmlContent.includes(`${widgetName}.css`)) {
          packageXmlContent = packageXmlContent.replace(
            '</files>',
            `    <file path="${zipCssPath}"/>\n        </files>`
          );
          zip.updateFile('package.xml', Buffer.from(packageXmlContent));
        }

        zip.writeZip(finalMpkPath);
      } catch (cssErr: any) {
        // Non-fatal: widget will load, but styles may be missing
        console.warn('[WARN] CSS injection into MPK failed:', cssErr.message);
      }
    }

    // Phase 4: Send the .mpk file
    console.log(`[4/4] Sending widget package...`);
    const distDirFinal = path.join(genDir, 'dist');
    const allDistFilesFinal = await fs.readdir(distDirFinal, { recursive: true });
    const mpkFilenameFinal = (allDistFilesFinal as string[]).find(f => f.endsWith('.mpk'));

    if (!mpkFilenameFinal) {
      throw new Error('Failed to find generated .mpk file in dist');
    }

    const mpkPathFinal = path.resolve(distDirFinal, mpkFilenameFinal);
    const mpkBaseName = path.basename(mpkFilenameFinal);
    res.download(mpkPathFinal, mpkBaseName, async (err) => {
      if (err) console.error('Download Error:', err);
      // Clean up temp build dir after download completes
      try {
        await fs.rm(tempDir, { recursive: true, force: true });
      } catch (cleanupErr) {
        console.warn('Cleanup warning:', cleanupErr);
      }
    });

  } catch (error: any) {
    console.error('Build Error:', error?.message || error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to build widget', details: error?.message });
    }
    try {
      await fs.rm(tempDir, { recursive: true, force: true });
    } catch (_) { }
  }
}

// --- Route 1: AI Generation Mode ---
app.post('/api/generate', async (req: Request, res: Response) => {
  const { widgetName, description } = req.body;

  if (!widgetName || !description) {
    return res.status(400).json({ error: 'widgetName and description are required' });
  }

  try {
    const aiResponse = await generateWidgetCode(description, widgetName);
    await buildWidgetPackage(widgetName, description, aiResponse.aiXml, aiResponse.aiJsx, res, aiResponse.aiCss, aiResponse.dependencies);
  } catch (error: any) {
    console.error('AI Generation Error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate widget via AI', details: error?.message });
    }
  }
});

// --- Route 2: Manual Bundle Mode ---
app.post('/api/bundle', async (req: Request, res: Response) => {
  const { widgetName, description, aiXml, aiJsx, aiCss, dependencies } = req.body;

  if (!widgetName || !description || !aiXml || !aiJsx) {
    return res.status(400).json({ error: 'widgetName, description, aiXml, and aiJsx are required for bundling' });
  }

  try {
    await buildWidgetPackage(widgetName, description, aiXml, aiJsx, res, aiCss, dependencies);
  } catch (error: any) {
    console.error('Manual Bundle Error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to bundle widget', details: error?.message });
    }
  }
});

// --- Start the Server ---
app.listen(PORT, () => {
  console.log(`✅ WidgetForge server running on http://localhost:${PORT}`);
  console.log(`   AI Provider: ${process.env.AI_PROVIDER || 'gemini'}`);
});

process.on('uncaughtException', (err) => {
  console.error('UNCAUGHT EXCEPTION:', err);
});

process.on('unhandledRejection', (reason) => {
  console.error('UNHANDLED REJECTION:', reason);
});
